<img src="photos/detox cure smoothie.jpg" alt="">
<h1>SE CONNECTER</h1>
<?php if (empty($_GET['err']) == false) : ?>
    <div class="alert alert-danger" role="alert"><?= $_GET['err'] ?></div>
<?php endif; ?>
<p>En vous connectant, vous pourrez accéder à votre liste de recettes favorites et en ajouter de nouvelles à votre liste. Si vous n'avez pas de compte, vous pouvez en créer un gratuitement.</p>
<a href="inscription.php">CREER UN COMPTE</a>
<form action="login.php" method="post" id="connect">
    <input type="email" name="email" id="email" placeholder="Adresse email" requiered>
    <input type="password" name="password" id="password" placeholder="Mot de passe" requiered>
    <input type="submit" value="SE CONNECTER">
</form>