<img src="photos/detox cure smoothie.jpg" alt="">
<h1>SE CONNECTER</h1>
<p>En vous connectant, vous pourrez accéder à votre liste de recettes favorites et en ajouter de nouvelles à votre liste. Si vous n'avez pas de compte, vous pouvez en créer un gratuitement.</p>
<a href="">CREER UN COMPTE</a>
<form action="" method="post">
    <input type="email" name="email" id="email" placeholder="Adresse email">
    <input type="password" name="password" id="password" placeholder="Mot de passe">
    <input type="submit" value="SE CONNECTER">
</form>