
<?php if($userSession->isAuthenticated() == true): ?> <!-- si l'utilisateur est connecter on affiche ces recttes favoritent -->
	<div class="container cxn">
		<div class="row">
        	<div class="col-md-12 bck">
			</div>
		</div>
		<div class="row">
        	<div class="col-md-12">
				<h1>MES RECETTES</h1>		
			</div>
		</div>
	</div>	
		<?php if(empty($fav)): ?> <!-- si on n'a pas de recette on affiche cela -->
			<p>Vous n'avez encore aucune recette dans vos favoris</p>
		<?php else : ?> <!-- sinon on affiche les recettes -->
			
			<div class="container">
			<div class="row blocProduits">
				<?php for($i = 0; $i < count($fav); $i++) : ?>
				<div class="col-md-4 produits">
					<div id="produit">
						<img src="photos/<?= $fav[$i]['Photo']; ?>" class="smoothiePics">
						<p><?= $fav[$i]['nbIngredient']; ?><img src="icons/fruits.png" alt="fruits" class="fruits"></p> 
						<a href="" class="fav" id="<?= $fav[$i]['Id_Recette']; ?>"><img src="icons/fullheart.png" alt="coeur"class="fullheart"></a>
					</div>
					<div class="nom">
						<a href="#" class="nomProduit"><?= $fav[$i]['Name']; ?></a>
					</div>
				</div>
				<?php endfor; ?>
			</div>
			</div>
		<?php endif; ?>
	<?php else : ?> <!-- sinon on le redirige vers la page de connection -->
	<?php header('Location: connexion.php?red=espace');
	exit(); ?>
	<?php endif; ?>