<?php $userSession = new UserSession(); ?> 
<?php if($userSession->isAuthenticated() == true): ?>
    <div class="container">
        <div class="col-md-12">
	        <img src="#">
			<h1>MES RECETTES</h1>
		</div>
	</div>
	<div class="container">
	    <div class="col-md-4">
	        <img src="#">
	    	<a href="#">Orange gourmandise</a>
	    </div>
	</div>
	<?php else : ?>
	<?php header('Location: connexion.php');
exit(); ?>
	<?php endif; ?>