<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SmoothieMaker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" /> 
</head>
<body>
    <header class="index">
        <div id="logo">
            <img src="logo/logoblanc.png" alt="logo">
        </div>
        <nav>
            <a href="index.php">Acceuil</a>    
            <a href="listesmoothies.php">Smoothies</a>   
            <a href="listerecettes.php">Recette</a>   
            <a href="lebar.php">Le bar</a>
            <?php $userSession = new UserSession(); ?> 
            <?php if($userSession->isAuthenticated() == true): ?>
                <p class="welcome">Bonjour <strong><?= htmlspecialchars($userSession->getFullName()) ?></strong> !</p>
                <a href="logout.php">Déconnexion</a>
            <?php else : ?>
                <a href="connexion.php">Se connecter</a>
            <?php endif; ?>
                    
        </nav>
        <h1>FABRICATION DE <br>SMOOTHIE ARTISANAL</h1>
<a href="" id="decouvrir">DECOUVRIR</a>
    </header>
 
    <div id="smoothie">     
    <h2>SmoothMaker</h2>
    <p>Votre producteur de smoothie artisanal à lyon</p>
    </div> 
    <img src="photos/milkshakefraise.png" alt="" id="milkshakefraise">
    <div class="container">
        <div class="row">
        <div class="col-md-6">
            <img src="photos/national-smoothie.png" alt="">
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis hic suscipit quae itaque vel dolores, deserunt maiores veritatis nam accusamus tempora magnam necessitatibus quod. Eligendi dolorem facilis quo pariatur animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores illum quia nemo sint modi iure, minus odio suscipit laborum vero ex non officia possimus, laboriosam autem velit cupiditate in ea.</p>
        </div>
        </div>
    </div>     
<div class="container">
    <h2>Nos smoothies</h2>
    <div class="row">
    <div class="col-md-4">
        <img src="" alt="">
        <h3></h3>
    </div>
    </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-5">
        <div>
            <h2>Nous trouver</h2>
            <p>Venez boire un coup smooth détente</p>
        </div>
        <div>
            <p>25, rue de la République
            69002 Lyon</p>
            <p>04 78 01 02 03</p>
            <p>smooth@maker.fr</p>
        </div>
        <div>
            <p>Venez profiter de la terrasse ombragée. Nos smoothies peuvent être servis accompagnés de petites douceurs gourmandes.</p>
        </div>
    </div>
    <div class="col-md-7">
        <div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d24408.522502402735!2d4.81742915187091!3d45.7645337933865!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4ea56197f0eb3%3A0x6618930dd84dbfdc!2s25+Rue+de+la+R%C3%A9publique%2C+69002+Lyon!5e0!3m2!1sfr!2sfr!4v1557390093797!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        </div>
    </div>
    <h2>Decouvrez les DIY smoothies</h2>
    <div class="row">
    <div class="col-md-5">
        <img src="photos/fondRose.jpg" alt="">
    </div>
    <div class="col-md-7">
            <h3>Nos smoothies, chez vous, pour vous.</h3>
            <p>Vous aimez nos smoothies ? Découvrez nos recettes uniques et originales à reproduire chez vous, directement.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Inventore, exercitationem? Blanditiis ea, nesciunt mollitia quaerat ipsam dicta consequuntur at dolor maxime fugiat ratione magnam, quibusdam qui natus adipisci libero accusantium?</p>
            <a href="">LES RECETTES</a>
    </div>
    </div>
</div>
        <footer>
            <h3>Partage ton smoothie sur les réseaux sociaux avec</h3>
            <h2>#smoothmaker</h2>
            <div>
                <img src="icons/instagram.png" alt="instagram logo">
                <img src="icons/facebook.png" alt="facebook logo">
                <small>2018 © Smooth Maker Lyon - Mentions légales - Contact</small>
            </div>          
        </footer>
    <script src="js/jquery-3.4.0.min.js"></script>
    <script src="js/main.js"></script>    
</body>
</html>



