<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SmoothieMaker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700,800,900" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Nixie+One" rel="stylesheet"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>


    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="css/main2.css" /> 
    <link rel="stylesheet" type="text/css" media="screen" href="css/main3.css" />  
</head>
<body class="titreh2">
    <header class="container-fluid backR"> 
    <div class="layer"> 
    <div class="row justify-content-between centralisation">
        <div class="tailleimage col-3">
            <img src="logo/logoblanc.png" alt="logo">
        </div>  
        <?php $userSession = new UserSession(); ?>
        <?php if($userSession->isAuthenticated() == true): ?>   
            <ul class="flexnavI col-6">
        <?php else : ?>
            <ul class="flexnavI col-4">
        <?php endif; ?> 
            <li><a href="index.php">ACCUEIL</a></li>
            <li><a href="listesmoothies.php">SMOOTHIES</a> </li>
            <li><a href="listerecettes.php">RECETTES</a> </li>
            <li><a href="lebar.php">LE BAR</a></li>
             
            <?php if($userSession->isAuthenticated() == true): ?>
            <li><p class="welcome">Bonjour <strong><?= htmlspecialchars($userSession->getFullName()) ?></strong> !</p></li>
            <li><a href="logout.php">DECONNEXION</a></li>                      
            <?php else : ?>
            <li><a href="connexion.php">SE CONNECTER</a></li>          
            <?php endif; ?> 
        </ul>     
    </div>
    <div class="row justify-content-around" >
        <ul class="col-md-4 titreG d-flex flex-column justify-content-center">
            <li><h1>FABRICATION DE <br>SMOOTHIE ARTISANAL</h1></li>
            <li><a href="listesmoothies.php" id="decouvrir">DECOUVRIR</a></li>
        </ul>
        <div class="col-md-5 imgD">
            <img src="photos/milkshakefraise.png" alt="milkshake" >
        </div>
    </div>  
    </div>      
    </header>
    <div class="container">
        <div class="row">
            <div classe="col-md-3" id="smoothie">     
            <h2>SmoothMaker</h2>
            <p>Votre producteur de smoothie artisanal à lyon</p>
            </div> 
        </div>
        <div class="row petitpadd">
        <div class="col-md-6 photoG">
            <img src="photos/national-smoothie.png" alt="">
        </div>
        <div class="col-md-6 texteD">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis hic suscipit quae itaque vel dolores, deserunt maiores veritatis nam accusamus tempora magnam necessitatibus quod. Eligendi dolorem facilis quo pariatur animi.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores illum quia nemo sint modi iure, minus odio suscipit laborum vero ex non officia possimus, laboriosam autem velit cupiditate in ea.</p>
        </div>
        </div>
    </div>     
<div class="container miseenavant">
    <h2 class="Nos-smoothies">Nos smoothies</h2>
    <hr/>
    <div class="row blocProduits">
    
    <?php foreach($recette as $index): ?>
        <div class="col-md-4 affiche produits">
                <img src="photos/<?= $index["Photo"] ?>" alt="image" class="smoothiePics">
                <div class="nom2">
                    <h3 class='nomProduit'><?= $index["Name"] ?></h3>
                </div>
        </div>
    <?php endforeach; ?>
       
    
    </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-5">
        <div class="trouver">
            <h2>Nous trouver</h2>
            <p>Venez boire un coup smooth détente</p>
        </div>
        <div class="rue">
            <p class="bold">25, rue de la République
            69002 Lyon</p>
            <p class="bold">04 78 01 02 03</p>
            <p class="bold">smooth@maker.fr</p>
            <p class="p">Venez profiter de la terrasse ombragée. Nos smoothies peuvent être servis accompagnés de petites douceurs gourmandes.</p>
        </div>
    </div>
    <div class="col-md-7">
        <div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d24408.522502402735!2d4.81742915187091!3d45.7645337933865!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4ea56197f0eb3%3A0x6618930dd84dbfdc!2s25+Rue+de+la+R%C3%A9publique%2C+69002+Lyon!5e0!3m2!1sfr!2sfr!4v1557390093797!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        </div>
    </div>
    <h2>Decouvrez les DIY smoothie</h2>
    <div class="row marginbot">
    <div class="col-md-5 photoG">
        <img src="photos/fondRose.jpg" alt="">
    </div>
    <div class="col-md-7 texteD">
            <h3>Nos smoothies, chez vous, pour vous.</h3>
            <p>Vous aimez nos smoothies ? Découvrez nos recettes uniques et originales à reproduire chez vous, directement.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Inventore, exercitationem? Blanditiis ea, nesciunt mollitia quaerat ipsam dicta consequuntur at dolor maxime fugiat ratione magnam, quibusdam qui natus adipisci libero accusantium?</p>
            <a href="listerecettes.php" class="les-recettes">LES RECETTES</a>
    </div>
    </div>
</div>
<footer class="container-fluid rose">
            <h3>Partage ton smoothie sur les réseaux sociaux avec</h3>
            <h2>#smoothmaker</h2>
            <div class="colone">
                <div class="RSlogo">
                    <img src="icons/instagram.png" alt="instagram logo">
                    <img src="icons/facebook.png" alt="facebook logo">
                </div>
                
                <small>2018 © Smooth Maker Lyon - Mentions légales - Contact</small>
            </div>          
        </footer>
    <script src="js/jquery-3.4.0.min.js"></script>
    <script src="js/main.js"></script>    
</body>
</html>



