<div class="container cxn">
    <div class="row">
    <div class="col-md-12 bck">
    </div> 
    <div class="col-md-12">
    <h1>S'INSCRIRE</h1>
    </div>    


<a href="connexion.php" class="cn">SE CONNECTER</a>
<form action="login.php" method="post" id="connect" class="clm">
    <input type="email" name="email" id="email" placeholder="Adresse email" requiered>
    <input type="password" name="password" id="password" placeholder="Mot de passe" requiered>
    <input type="password" name="cpassword" id="cpassword" placeholder="Confirmation mot de passe" requiered>
    <input type="text" name="LastName" id="LastName" placeholder="Nom" requiered>
    <input type="text" name="FirstName" id="FirstName" placeholder="Prénom" requiered>
    <input type="submit" value="S'INSCRIRE">
</form>
</div>
</div>