<img src="photos/detox cure smoothie.jpg" alt="">
<h1>S'INSCRIRE</h1>
<a href="connexion.php">SE CONNECTER</a>
<form action="login.php" method="post">
    <input type="email" name="email" id="email" placeholder="Adresse email" requiered>
    <input type="password" name="password" id="password" placeholder="Mot de passe" requiered>
    <input type="password" name="cpassword" id="cpassword" placeholder="Confirmation mot de passe" requiered>
    <input type="text" name="LastName" id="LastName" placeholder="Nom" requiered>
    <input type="text" name="FirstName" id="FirstName" placeholder="Prénom" requiered>
    <input type="submit" value="SE CONNECTER">
</form>