<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SmoothieMaker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700,800,900" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Nixie+One" rel="stylesheet"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>


    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="css/main2.css" /> 
    <link rel="stylesheet" type="text/css" media="screen" href="css/main3.css" />  
</head>
<body>
    <header class="container-fluid ">
        <div class="row justify-content-between">
            <div class="tailleimage">
                <img src="logo/logo.png" alt="logo">
            </div>
            <!-- <nav class="alignementnav"> -->
                <ul class="flexnav col-4">
                    <li><a href="index.php">ACCUEIL</a></li>
                    <li><a href="listesmoothies.php">SMOOTHIES</a> </li>
                    <li><a href="listerecettes.php">RECETTES</a> </li>
                    <li><a href="lebar.php">LE BAR</a></li>
                    <?php $userSession = new UserSession(); ?> 
                    <?php if($userSession->isAuthenticated() == true): ?>
                    <li><p class="welcome">Bonjour <strong><?= htmlspecialchars($userSession->getFullName()) ?></strong> !</p></li>
                    <li><a href="logout.php">DECONNEXION</a></li>                      
                    <?php else : ?>
                    <li><a href="connexion.php">SE CONNECTER</a></li>          
                    <?php endif; ?> 
                </ul>                                                                                  
            <!-- </nav> -->
        </div>
    </header>
        <?php include $template.".phtml"; ?>
        <footer class="container-fluid rose">
            <h3>Partage ton smoothie sur les réseaux sociaux avec</h3>
            <h2>#smoothmaker</h2>
            <div class="colone">
                <div class="RSlogo">
                    <img src="icons/instagram.png" alt="instagram logo">
                    <img src="icons/facebook.png" alt="facebook logo">
                </div>
                
                <small>2018 © Smooth Maker Lyon - Mentions légales - Contact</small>
            </div>          
        </footer>
    <script src="js/jquery-3.4.0.min.js"></script>
    <script src="js/main.js"></script>    
</body>
</html>