<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SmoothieMaker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Nixie+One" rel="stylesheet"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>


    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" /> 
</head>
<body>
    <header>
        <div class="logo">
            <img src="logo/logo.png" alt="logo">
        </div>
        <nav>
            <a href="index.php">Acceuil</a>    
            <a href="listesmoothies.php">Smoothies</a>   
            <a href="listerecettes.php">Recette</a>   
            <a href="lebar.php">Le bar</a>
            <?php $userSession = new UserSession(); ?> 
            <?php if($userSession->isAuthenticated() == true): ?>
                <p class="welcome">Bonjour <strong><?= htmlspecialchars($userSession->getFullName()) ?></strong> !</p>
                <a href="logout.php">Déconnexion</a>
            <?php else : ?>
                <a href="connexion.php">Se connecter</a>
            <?php endif; ?>       
        </nav>
    </header>
        <?php include $template.".phtml"; ?>
        <footer>
            <h3>Partage ton smoothie sur les réseaux sociaux avec</h3>
            <h2>#smoothmaker</h2>
            <div>
                <img src="icons/instagram.png" alt="instagram logo">
                <img src="icons/facebook.png" alt="facebook logo">
                <small>2018 © Smooth Maker Lyon - Mentions légales - Contact</small>
            </div>          
        </footer>
    <script src="js/jquery-3.4.0.min.js"></script>
    <script src="js/main.js"></script>    
</body>
</html>