<div>
    <img src="photos/smooth.jpg" alt="photo smoothie">
    <div>
        <h1>NOS RECETTES</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div>
            <p>Des recettes simples, à réaliser chez vous. Petits-déjeuners, goûters, nos recettes originales raviront les plus petits comme les plus grands. Nos recettes sont faîtes avec des fruits bio, ce n'est pas indispensable mais nous vous le recommandons. Il est également préférable d'utiliser des fruits de saison.</p>
            <a href="espaceperso.php"><img src="icons/emprycolorheart.png" alt="coeur"> VOS RECETTES FAVORITES</a>
        </div>
    </div>
    <div class="col-md-4">
        <img src="icons/fruitscolor.png" alt="fruits">
        <img src="icons/emprycolorheart.png" alt="coeur">
        <img src="photos/" alt="img recette">
        <p>Titre</p>
    </div>
</div>