<div class="container">
    <div class="row">
        <div class="col-md-6 divimg ">

        </div>
        <div class="col-md-6 float-right">
                <h1 class="titre">NOS SMOOTHIES</h1>
        </div>
    </div>
    <div class="row">
        <div class="intro">
            <p>Des smoothies fait maison, avec des produits bio et de saison. Au plus possible nous favorisons les producteurs locaux afin de vous proposer des produits Eco-responsable au possible et bla bla bla.</p>
            <a href="lebar.php">VENEZ NOUS DECOUVRIR</a>
        </div>
    </div>
    <div class="row blocProduits">
        <?php foreach ($smoothies as $smoothie): ?>
            <div class="col-md-4 produits">
                <div id="produit">
                    <a href="lebar.php">
                        <img src="photos/<?=$smoothie['Photo']?>" alt="img recette" class="smoothiePics">
                        <div class="nom2">
                            <p class="nomProduit2"><?=$smoothie['Name']?></p>
                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>