<div>
    <img src="photos/smooth.jpg" alt="photo smoothie">
    <div>
        <h1>NOS RECETTES</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div>
            <p>Des recettes simples, à réaliser chez vous. Petits-déjeuners, goûters, nos recettes originales raviront les plus petits comme les plus grands. Nos recettes sont faîtes avec des fruits bio, ce n'est pas indispensable mais nous vous le recommandons. Il est également préférable d'utiliser des fruits de saison.</p>
            <a href="espaceperso.php"><img src="icons/emprycolorheart.png" alt="coeur"> VOS RECETTES FAVORITES</a>
        </div>
    </div>
        <?php foreach ($smoothies as $smoothie): ?>

		    <div class="col-md-4">
		    	<img src="photos/<?= $smoothie['Photo']; ?>">
		    	<p><?= $smoothie['nbIngredient']; ?><img src="icons/fruitscolor.png" alt="fruits"></p> 
		    	<a href="" class="fav" id="<?= $smoothie['Id']; ?>">
                <?php if ($smoothie['fav'] == 'true'):?>
                <img src="icons/fullheart.png" alt="coeur"></a>
                <?php else : ?>
                <img src="icons/emprycolorheart.png" alt="coeur"></a>
                <?php endif; ?>
                
		    	<a href="#" id='<?= $smoothie['Id'] ?>' class="recette"><?= $smoothie['Name']; ?></a>
		    </div>
		<?php endforeach; ?>
  
</div>