<div>
    <img src="photos/smooth.jpg" alt="photo smoothie">
    <div>
        <h1>NOS SMOOTHIEs</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div>
            <p>Des smoothies fait maison, avec des produits bio et de saison. Au plus possible nous favorisons les producteurs locaux afin de vous proposer des produits Eco-responsable au possible et bla bla bla.</p>
            <a href="espaceperso.php"><img src="icons/emprycolorheart.png" alt="coeur"> VOS RECETTES FAVORITES</a>
        </div>
    </div>
    <div class="col-md-4">
        <img src="photos/" alt="img recette">
        <p>Titre</p>
    </div>
</div>