<div class="container">
    <div class="row">
        <div class="col-md-6 divimg ">
            
        </div>
        <div class="col-md-6 float-right">
            <h1 class="titre">NOS RECETTES</h1>
        </div>
    </div>
    <div class="row">
        <div class="intro">
            <p>Des recettes simples, à réaliser chez vous. Petits-déjeuners, goûters, nos recettes originales raviront les plus petits comme les plus grands. Nos recettes sont faîtes avec des fruits bio, ce n'est pas indispensable mais nous vous le recommandons. Il est également préférable d'utiliser des fruits de saison.</p>
            <a href="espaceperso.php"><img src="icons/emptyheart.png" alt="coeur">  VOS RECETTES FAVORITES</a>
        </div>
    </div>
        <div class="row blocProduits">
            <?php foreach ($smoothies as $smoothie): ?>

                <div class="col-md-4 produits">
                    <div id="produit">
                        <img src="photos/<?= $smoothie['Photo']; ?>" class="smoothiePics">
                        <p><?= $smoothie['nbIngredient']; ?> <img src="icons/fruits.png" alt="fruits" class="fruits"></p>
                        <a href="" class="fav" id="<?= $smoothie['Id']; ?>">
                            <?php if (array_key_exists('fav', $smoothie) && ($smoothie['fav'] == 'true')):?>
                            <img src="icons/fullheart.png" alt="coeur plein" class="fullheart"></a>
                            <?php else : ?>
                            <img src="icons/emptyheart.png" alt="coeur vide" class="emptyheart"></a>
                            <?php endif; ?>
                    </div>
                    <div class="nom">
                        <a href="#" id='<?= $smoothie['Id'] ?>' class="recette nomProduit"><?= $smoothie['Name']; ?></a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
</div>