
	<div>
		<img src="photos/smoothie-detox.jpg">  
		<h1>GREEN OXYDANT</h1> 
	</div>
	<div>
		<a href="#"><img src="icons/emprycolorheart.png"> AJOUTER CETTE RECETTE EN FAVORIS</a>
	</div>
	<div class="container">
		<div class="col-md-6">
			<h3>INGREDIENTS</h3>
			<p>Pour 2 personnes:</p>
			<ul>
				<li>100gr d'épinards</li>
				<li>30gr de raisin sans pépin</li>
				<li>1 pomme</li>
				<li>5cl de jus de citron</li>
				<li>20cl d'eau</li>
				<li>50gr de glaçons</li>
			</ul>
		</div>
		<div class="col-md-6">
			<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal </p>
			<h4>Etapes</h4>
			<ul>
				<li>Bien nettoyer les ingrédients</li>
				<li>Eplucher les pommes et les couper en morceaux</li>
				<li>Si les raisin contiennent des pépins, pensez à les retirer</li>
				<li>its layout. The point of using Lorem Ipsum is that it has a more-or-less normal </li>
				<li>its layout. The point of using Lorem Ipsum </li>
				<li>Servir frais</li>
			</ul>
			<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages</p>
		</div>
		
	</div>

